name: Ibis Next eBook Generation

on:
  push:
    branches: [main]
    paths:
      - 'ebook/**'
      - 'action.yml'
      - 'entrypoint.sh'
  pull_request:
    branches: [main]
    paths:
      - 'ebook/**'
      - 'action.yml' 
      - 'entrypoint.sh'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Ibis Next Export Files
        uses: ./
        with:
          ibis_path: "./ebook/en"
          ibis_branch: "main"
          email: "bobby@bobbyiliev.com"
          commit_message: "ðŸ“š Updated Ibis Next Exported Files"
          php_version: "8.2"
